using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CareHomeMock.Models
{
    /// <summary>
    /// One-time-password to post a review.
    /// Generated by CareManager.
    /// Consumed to post by Visitor(Patient or his Family).
    /// </summary>
    public class Otp
    {
        [Key]
        public int OtpId { get; set; }

        public DateTime Expires { get; set; }

        /// <summary>
        /// 4 digits verification code.
        /// </summary>
        public string VerificationCode { get; set; }

        /// <summary>
        /// CareManager generated this OTP for who.
        /// </summary>
        public PatientType PatientType { get; set; }

        public int CareManagerId { get; set; }

        /// <summary>
        /// CareManager who has generated this OTP.
        /// </summary>
        [ForeignKey("CareManagerId")]
        public virtual CareManager CareManager { get; set; }
    }
}