// <auto-generated />
namespace CareHomeMock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DropComplexType_CareHome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropComplexType_CareHome));
        
        string IMigrationMetadata.Id
        {
            get { return "201412011248408_DropComplexType_CareHome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
