// <auto-generated />
namespace CareHomeMock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Add_License : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_License));
        
        string IMigrationMetadata.Id
        {
            get { return "201412051600315_Add_License"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
