// <auto-generated />
namespace CareHomeMock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Index_CareHome_Name_Traits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Index_CareHome_Name_Traits));
        
        string IMigrationMetadata.Id
        {
            get { return "201412160342402_Index_CareHome_Name_Traits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
